# Generated by Django 5.0.4 on 2025-03-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YoloObjectDetectionAPI', '0006_customer_printingorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printingorder',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='PrintingOrder',
        ),
    ]
